version: "3.8"
services:
  blogpy_postgresql:
    image: postgres:latest
    container_name: blogpy_postgresql
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - blogpy_network

volumes:
  bloqpy_postgresql:
    external: true
networks:
  blogpy_network:
    external: true
